name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go mod download
      - run: go test -cpu=1,2 -race ./...

  image:
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/setup-qemu-action@v3

      - uses: docker/metadata-action@v5
        id: docker_meta
        with:
          images: ghcr.io/tklein1801/concourse-discord-alert-resource
          tags: |
            type=edge
            type=semver,pattern={{raw}}
          flavor: |
            latest=auto

      - name: Build test image
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          load: true
          push: false
          tags: ghcr.io/tklein1801/concourse-discord-alert-resource:dev
      - run: >
          echo "{\"source\":{\"url\":\"${{ vars.DISCORD_WEBHOOK }}\"}}" | docker run -i
          -e "ATC_EXTERNAL_URL=https://ci.example.com"
          -e "BUILD_TEAM_NAME=main"
          -e "BUILD_PIPELINE_NAME=github-actions"
          -e "BUILD_JOB_NAME=test"
          -e "BUILD_NAME=$GITHUB_RUN_ID-$GITHUB_RUN_NUMBER"
          -e "BUILD_PIPELINE_INSTANCE_VARS={\"ref\":\"$GITHUB_REF_NAME\"}"
          ghcr.io/tklein1801/concourse-discord-alert-resource:dev
          /opt/resource/out $PWD
